<?php
echo $this->headTitle('Add new user');
?>

    <div class="row">
        <div class="col-md-8"> <h1> Add new user</h1>
        </div>
        <div class="col-md-4">  </div>
    </div>
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <?php

            $form = $this->form;
            $form->setAttribute('action', $this->url('school',array('action'=>'adduser')));

            $form->get('group_id')->setValueOptions($this->groups);

            $form->prepare();

            echo $this->form()->openTag($form);
            echo $this->formRow($form->get('name')) . "</br>";
            echo $this->formRow($form->get('group_id')) . "</br>";
            echo $this->formRow($form->get('addusers')) . "</br>";
            echo $this->form()->closeTag();


            ?>
        </div>
        <div class="col-md-4">  </div>
    </div>
